### ISSUE TITLE
Permalink to non-public object behavior

### ISSUE THREAD

**Issue by jt112** [duke-libraries/ddr-public#102]
User Matthew works in the bestest University Archives in the whole Duke University and manages collections in a software system, ArchivesSpace (AS).  Matthew wants to store resolvable repository permalinks to his restricted access colllections in AS.   This permalink would link through the library resolver to N2T and resolve to DDR Public.  Because the object isn't published, DDR Public should display a message explaining that the item is not published, provide a link to the object in the staff interface, and provide an email address for assistance.

The language could be:

Sorry!  Access to this object is restricted to Duke University Libraries staff.  Staff may access this object at $url.  For assistance, contact repository-help@duke.edu

**Comment by dchandekstark** [comment]
Will patch 1.x branch by modifying the rescue_from block in CatalogController.

**Comment by dchandekstark** [comment]
Now depends on #106
