### ISSUE TITLE
Improve performance of Collection facet

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-public#103]
Doing a find on each Collection is too expensive.  And the sorting (https://github.com/duke-libraries/ddr-public/blob/develop/app/helpers/application_helper.rb#L22) may result in duplicate finds.

We should be able to the titles for all collections in a single solr query and stash it somewhere.

**Comment by dchandekstark** [comment]
This Solr query might be helpful:

q=active_fedora_model_ssi:Collection%20AND%20workflow_state_ssi:published&fl=internal_uri_ssi,title_ssi

I assume it's only needed in the index view.  You could turn the results in to a hash with the URIs as keys to get the title in the facet sort algorithm.

**Comment by dchandekstark** [comment]
Here's a sketch of a method (not tested):

```ruby
def collections
    @collections ||=
      begin
        response, docs = get_search_results(q: "active_fedora_model_ssi:Collection",
                                            fl: "internal_uri_ssi,title_ssi",
                                            rows: 100)
        docs.each_with_object({}) do |doc, memo|
          memo[doc["internal_uri_ssi"]] = doc["title_ssi"]
        end
      end
  end
```

**Comment by coblej** [comment]
@dchandekstark Where do you imagine a method like the one you sketch out above would go?

**Comment by dchandekstark** [comment]
It can go in a helper module I think since get_search_results is a helper method.

**Comment by coblej** [comment]
I tried putting it in catalog_helper.rb but either I didn't get quite right or I don't understand the scope of the @collections variable.  It looked like @collections was getting rebuilt on every request.  Is that right / expected?

**Comment by dchandekstark** [comment]
Yes, it will get rebuilt every request. We can consider stashing it in session, bit I would think this offers a substantial improvement, no?


Jim Coble <notifications@github.com> wrote:


I tried putting it in catalog_helper.rb but either I didn't get quite right or I don't understand the scope of the @collections<https://github.com/collections> variable. It looked like @collections<https://github.com/collections> was getting rebuilt on every request. Is that right / expected?

-

**Comment by dchandekstark** [comment]
@coble Note that you shouldn't use the variable directly because it's lazily loaded. It will be nil if you try to use it directly before it's been loaded.

**Comment by coblej** [comment]
@dchandekstark Right.  Have a PR about ready.
