### ISSUE TITLE
max_per_page is set too high

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-public#127]
https://github.com/duke-libraries/ddr-public/blob/develop/app/controllers/catalog_controller.rb#L195

Current value of 999 causes, e.g., very inefficient display of a collection having hundreds of items.

/cc @coblej

**Comment by dchandekstark** [comment]
@corylown @seanaery I'd like to give this issue a bump since the UX is pretty bad for a non-DC collection.  I believe the reason it was set high predates Tripod3 work and is no longer relevant (IIRC it was a workaround to a pagination-within-pagination problem).

**Comment by corylown** [comment]
@dchandekstark we'll prioritize this.
