### ISSUE TITLE
In OpenSeadragon when viewing the last item the next button zooms the image when clicked

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-public#138]
@seanaery I noticed that when you get to the last item using the prev/next buttons in OpenSeadragon, clicking on the next button starts to zoom in on the image once it's been deactivated.

**Comment by seanaery** [comment]
Good catch. Looks like it's ghosting the button when inactive. I.e., the button is no longer really there so clicking the disabled state clicks what's behind it: the seadragon container, which zooms the image.
