### ISSUE TITLE
Image server request for info.json and SSL on repository-dev

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-public#151]
@seanaery I'm not sure exactly what the root cause is, but it looks like there's a problem making the request to the image server for info.json

11:08:34 FATAL: 
ActionView::Template::Error (redirection forbidden: http://repository-dev.lib.duke.edu/iipsrv/?IIIF=/srv/repo_deriv/multires_image_dev/f/5/4e/f54e8741-4a2d-47cd-a911-3ec67394876e/dscsi050050010.ptif/info.json -> https://repository-dev.lib.duke.edu/iipsrv/?IIIF=/srv/repo_deriv/multires_image_dev/f/5/4e/f54e8741-4a2d-47cd-a911-3ec67394876e/dscsi050050010.ptif/info.json):
    35: 
    36: <% if image_item_tilesources(@document, @document_list) %>
    37:   
    38:    <%= render partial: "show_seadragon", locals: { aspectratio: image_item_aspectratio(@document, @document_list), imagecount: image_item_tilesources(@document, @document_list).length } %> 
    39:   <%= render partial: "show_multires_image_download", locals: { image_path: multi_image_sorted_paths(@document, @document_list).first, imagecount: image_item_tilesources(@document, @document_list).length } %> 
    40: <% end %>
    41: 
  app/helpers/application_helper.rb:182:in `image_item_aspectratio'
  app/views/catalog/_display_multi_image.html.erb:38:in `_app_views_catalog__display_multi_image_html_erb___4543230331721250120_64199360'
  app/views/catalog/_show_multi_image_item.html.erb:1:in `_app_views_catalog__show_multi_image_item_html_erb__262288191138801485_63168000'
  app/helpers/render_partials_helper.rb:39:in `render_document_partial'

**Comment by seanaery** [comment]
Interesting. Not sure why there's a 'redirection forbidden' error, but I suspect we should change the IMAGE_SERVER_URL value in local_env.yml to specify https rather than be protocol-relative.

**Comment by corylown** [comment]
Update on this: SSL is not set up for the image server on collections-01. I have a ticket in with Derrek to get this configured and added to resolve the issue.

**Comment by seanaery** [comment]
Update: this is still not working, though our presumed blockers are resolved. New error message:
```
12:01:00 FATAL: 
ActionView::Template::Error (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed):
```

The image_server_url is correctly set:
```
2.1.2 :001 > Ddr::Models.image_server_url
 => "https://repository-dev.lib.duke.edu/iipsrv/" 
```

The reverse proxy is in place and working correctly. SSL is set up on collections-01. A path like the following to image data is working:
https://repository-dev.lib.duke.edu/iipsrv/?IIIF=/srv/repo_deriv/multires_image_dev/6/7/c5/67c57e05-4f78-436a-965e-c051271f22a6/mfb108.ptif/info.json

In our application_helper, this JSON.load method is being denied even though the SSL cert is apparently valid:
```
imagedata = JSON.load(open(urls.first))
```

**Comment by seanaery** [comment]
@coblej @dchandekstark I'm curious -- any ideas or experience loading JSON data from a URL over https?

**Comment by dchandekstark** [comment]
I have had the same problems and have had to set the HTTP connection verify_mode to `OpenSSL::SSL::VERIFY_NONE`. See https://github.com/duke-libraries/ddr-aux-client/blob/v1.0.0/lib/ddr_aux/client/connection.rb#L12-L19.

**Comment by seanaery** [comment]
@dchandekstark Excellent, thanks for the tip.
