### ISSUE TITLE
Account for case where struct_map is nil

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-public#155]
@seanaery On repo-dev, for whatever reason, the blake collection does not have any struct_map data associated with it. When the _display_multi_image.html.erb partial attempts to use some of the helpers in application_helper.rb I'm seeing an  "ActionView::Template::Error (undefined method `each' for nil:NilClass)" error in the logs. I think this is because sorted_pids returns nil if struct_map doesn't exist for the document, but the multi_image_sorted_paths method does not account for sorted_pids being nil.

Relevant lines in application_helper.rb

https://github.com/duke-libraries/ddr-public/blob/develop/app/helpers/application_helper.rb#L111-L139

**Comment by seanaery** [comment]
Good catch -- just an oversight on my part. I'll fix it today.
