### ISSUE TITLE
date fields not searchable via keyword search

### ISSUE THREAD

**Issue by seanaery** [duke-libraries/ddr-public#193]
I noticed that entering a year (e.g., 1885)  in the keyword search box returns no results, even using wildcards. In our existing digital collections UI, we see that about 10-15% of our or most frequent keyword searches are (or include) a year, so it'd be helpful to fix this.

**Comment by corylown** [comment]
Fixed by adding Ddr::Index::Fields::YEAR_FACET to the qf parameter sent to Solr with each keyword query request.
