### ISSUE TITLE
date range facet 'Unknown' link leads to components

### ISSUE THREAD

**Issue by seanaery** [duke-libraries/ddr-public#196]
In the date range facet, the Unknown link under the histogram has result count 6,044. Clicking that link leads to a result view showing all component objects in the collection.  

Short of making that line show/link to only item objects, we could hide it from the display, e.g.:  
```
#facet-year_facet_iim ul.missing { display: none; }
```
CC: @corylown

**Comment by corylown** [comment]
Hid this link with CSS in the 2.0.1 hot fix.
