### ISSUE TITLE
facet links yield no browser loading indicator while next page loads

### ISSUE THREAD

**Issue by seanaery** [duke-libraries/ddr-public#207]
Clicking on a facet link leads you to a search result page eventually (e.g., within 1-3 seconds). But while you wait, the standard "loading" indicator in the browser doesn't display (e.g., Chrome & Firefox: spinner in tab where favicon normally appears, Safari: blue progress indicator as background to address bar). This can give the illusion that nothing is loading.

With Javascript off, this doesn't happen, so it appears Javascript-initiated requests don't trigger the loading indicator and there's some JS involved. This bug is present in the Blacklight demo ( http://demo.projectblacklight.org/?f%5Bformat%5D%5B%5D=Book ), but several Blacklight shops seem to have gotten around it.

**Comment by corylown** [comment]
This could be related to turbolinks, which is turned on in Rails by default:

https://github.com/rails/turbolinks

It's simple to remove:

http://blog.steveklabnik.com/posts/2013-06-25-removing-turbolinks-from-rails-4
