### ISSUE TITLE
Add config setting to require authentication

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-public#228]
This is needed for use in the protected data network.

**Comment by corylown** [comment]
@dchandekstark is this something you've added to the PDN already? If so, can you share how it's implemented so I can add it as a configurable option to ddr-public?

**Comment by dchandekstark** [comment]
Just insert into `ApplicationController`:

```ruby
before_action :authenticate_user!
```

**Comment by dchandekstark** [comment]
So, you could do something like:

```ruby
before_action :authenticate_user!, if: :authentication_required?

def authentication_required?
  Ddr::Public.require_authentication
end
```
