### ISSUE TITLE
Need to customize branding for PDN

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-public#229]
We want a different logo for the protected data network to clearly distinguish the interface.

/cc @jt112

**Comment by jt112** [comment]
This is the most recent one from Michael.

**Comment by seanaery** [comment]
![pdr-logo](https://cloud.githubusercontent.com/assets/3933756/12486428/b7b56866-c030-11e5-84aa-d3fbc3e55f02.png)

<img width="1098" alt="screen shot 2016-01-21 at 11 20 34 am" src="https://cloud.githubusercontent.com/assets/3933756/12486503/07815e72-c031-11e5-9147-6895d8ca73c5.png">

Here's a new one (a PNG) and what it'd look like in context. Old ddr-public used to use variable $logo_image set on application.css.scss. However, we significantly changed the mast from Blacklight's defaults; now the mast sets the (two) logos here:
https://github.com/duke-libraries/ddr-public/blob/develop/app/views/shared/_header_navbar.html.erb#L17

Maybe we could refactor that piece back into a variable that'd be customizable between DDR & PDR? Let me know what you think would be the best approach.

**Comment by seanaery** [comment]
Should also mention, this new PDR .PNG is the same size as the DIGITAL REPOSITORY logo and doesn't need anything different w/r/t CSS for display.
