### ISSUE TITLE
"Login to download" link missing?

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-public#236]
In ddr-public 1.x, we displayed a "Login to download" link on a Component show view if the file was not publicly downloadable and the user was not logged in.  Perhaps this got lost in the transition to 2.x?

/cc @coblej @seanaery @corylown

**Comment by coblej** [comment]
@dchandekstark In 1.x (and the same is true in 2.x, I believe), the "Login to download" _only_ displays if the REGISTERED group has download rights.  There are probably few, if any, published objects for which this currently true.  So, this is probably not a bug.  It may no longer be the desired behavior but it was a deliberate design decision at the time.
/cc @seanaery @corylown

**Comment by dchandekstark** [comment]
@coblej OK, I remembered incorrectly. I removed the bug label (and added a question mark to the title), but perhaps it's worth reconsidering the UI/UX issues here. It's a hard problem since the user is not forced to login, and we don't know if the anonymous user will be able to download the file after logging in.

**Comment by coblej** [comment]
@dchandekstark Right, that's the reason behind the decision that was made at the time, that we would add the "Login to Download" button only if everyone who could log in would then be able to download the content.  As you say, it's a hard problem.  One idea that was floated at the time was some kind of pop-up that say clearly who could and could not download if they logged in but we didn't want to tackle that at the time.

**Comment by dchandekstark** [comment]
@coblej I would consider the specific authorization information privileged. However, perhaps something along the lines of "restricted to authorized individuals and groups" in lieu of license information.

**Comment by corylown** [comment]
@coblej @dchandekstark This behavior should not have changed in 1.x vs 2.x. The only difference is the CSS applied. One approach to cases where only certain authorized users/groups will be able to download an item would be to display the login link but contextualize it differently. The button could be preceded by a note such as: "Access to this file is restricted to authorized users and groups. Log in to verify authorization to download" -- or something like that.

**Comment by seanaery** [comment]
@corylown @coblej @dchandekstark I support including a line with something to the effect of these last two comments. That should help the UX quite a bit when users encounter restricted resources. The word "login" could link to the login action, and we could do something visual (a lock icon?) to make it abundantly clear that the item or component is restricted.

**Comment by jt112** [comment]
That seems like a lot of text, but I trust it will turn out well.

Jim Tuttle
Head, Digital Repository Services
Duke University Libraries
919.613.6831

On Dec 2, 2015, at 10:19, Sean Aery <notifications@github.com<mailto:notifications@github.com>> wrote:


@corylown<https://github.com/corylown> @coblej<https://github.com/coblej> @dchandekstark<https://github.com/dchandekstark> I support including a line with something to the effect of these last two comments. That should help the UX quite a bit when users encounter restricted resources. The word "login" could link to the login action, and we could do something visual (a lock icon?) to make it abundantly clear that the item or component is restricted.

-

**Comment by seanaery** [comment]
We'll pick this thread back up soon. Our recent work with DVS collections necessitates us (for some collections) to display metadata publicly but restrict file downloads to authorized Duke users, so we'll have to make this clear in the UI.
