### ISSUE TITLE
Multi image items with many components are slow to load

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-public#249]
For example: https://repository.lib.duke.edu/dc/rushbenjaminandjulia/brpst032001

**Comment by seanaery** [comment]
A few initial ideas...

One thing that's almost certainly contributing to the slowness is that the "Files" section that lists all the components for a file--complete with thumbnail and not paginated--is actually rendering in the item page below the metadata but is wrapped in a div with display:none.  I'm sure we'll find many other optimization opportunities as well.

I think OpenSeadragon uses lazy-loading so it's likely only trying to load assets as needed while a user navigates an item. 

The methods in use by the multi-image items for assembling the array of tilesource paths sequentially by structmap order are probably expensive, get called more times than necessary, and hopefully are ripe for replacement.

**Comment by corylown** [comment]
Despite not loading the file list and some improvements to the methods used to assemble the tilesource arrays, this is still an issue for multi image items with hundreds of components, such as:

https://repository.lib.duke.edu/dc/rushbenjaminandjulia/brpst032001
