### ISSUE TITLE
Finding aid partial cached per collection; causes incorrect "View In Context" links

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-public#278]
Currently the _show_finding_aid.html.erb partial is cached per collection. This means that the aspace_id in the link to "View In Context" gets cached as well. After the initial caching of the partial all items in the collection will have a link to the same aspace_id.  We need to ensure that we cache just the portion of the template that applies to every item in the collection or turn off caching for this partial.

**Comment by seanaery** [comment]
Ouch, good catch. I should've put that in a separate partial.
