### ISSUE TITLE
suppress Analytics tracking in preproduction

### ISSUE THREAD

**Issue by seanaery** [duke-libraries/ddr-public#307]
Looks like the Google Analytics tracking script is rendering in our template HTML even in preproduction despite this line https://github.com/duke-libraries/ddr-public/blob/develop/app/views/layouts/blacklight.html.erb#L29 

Ideally, we'd only be collecting data for production traffic.

**Comment by coblej** [comment]
Just FYI, in case it's not clear, the production, pre-production, and development servers are all running the Hydra apps in the 'production' environment as far as Rails is concerned.  If you'd like suggestions on how to restrict the line in question to only running on the production server, just let me (or David) know.

**Comment by seanaery** [comment]
Resolved this issue in a revised/improved way via #313 as a separate concern from the preview banner -- this now necessitates adding the following to local_env.yml on the production server only (sometime before the next release is tagged/deployed): 
`TRACK_GOOGLE_ANALYTICS: 'true'`
