### ISSUE TITLE
Download template missing for single image items

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-public#336]
@seanaery I'm not sure when this bug was introduced, but the application is looking for a template that doesn't exist when a single image item's show view is called, such as for Mangum collection items.

Example: https://repository-pre.lib.duke.edu/dc/hmp/hmpgp21653

Error in the log:
```
08:36:42 INFO: Completed 500 Internal Server Error in 513ms 
08:36:42 FATAL: 
ActionView::Template::Error (Missing partial digital_collections/_item_options_download_image, catalog/_item_options_download_image, application/_item_options_download_image
```

**Comment by seanaery** [comment]
@corylown Likely introduced when I refactored the item download UI to accommodate A/V items. Must have missed something. I'll plan to fix this today.
