### ISSUE TITLE
Browse ___ Items button on collection portal should show only count of published items

### ISSUE THREAD

**Issue by seanaery** [duke-libraries/ddr-public#338]
Currently appears to display the total count of items, published + unpublished within a collection. E.g., for dukechapel collection the button says 2,881 but results view shows 2,767 items.

**Comment by dchandekstark** [comment]
Is the facet number correct?

**Comment by seanaery** [comment]
@dchandekstark Facet number (i.e., from DDR homepage to Collection = Duke Chapel Recordings) is correct-ish. It shows 2,768 because it includes the collection itself in the tally a result. We may want to refine that in the future, but that's likely out-of-scope for current sprint.

**Comment by dchandekstark** [comment]
Yes, that has also been observed in the PDR.
