### ISSUE TITLE
long collection titles with showcase display forces scrolling

### ISSUE THREAD

**Issue by seanaery** [duke-libraries/ddr-public#357]
For digital collections, with a long title and/or abstract displayed to the left of a collection portal showcase, the containing box scrolls when exceeded in height by its contents. This looks funny and could potentially be problematic if it hides the Browse Items button. 

![screen shot 2016-04-19 at 3 54 14 pm](https://cloud.githubusercontent.com/assets/3933756/14653542/6aaba30c-0647-11e6-9384-88dde2e71e24.png)

**Comment by corylown** [comment]
Reopening because this still seems to be an issue at narrower widths.

<img width="1048" alt="screen shot 2016-04-22 at 7 46 42 am" src="https://cloud.githubusercontent.com/assets/458247/14740718/173ba392-085f-11e6-9e59-5648209731dd.png">

**Comment by seanaery** [comment]
D'oh, I forgot to check that--good catch. I'll fix it today.
