### ISSUE TITLE
Add ability to facet by EAD ID

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-public#365]
This may require a change to ddr-models to index ead_id as a facet. It will also require a method that translates the ead_id to the name of the collection guide.

While for many digital collections the ead id is the same for all items, this isn't always the case (see ESR https://repository-pre.lib.duke.edu/dc/esr) and providing a way to browse by EAD ID may be important for some stakeholders and users.

**Comment by dchandekstark** [comment]
@corylown I think `Ddr::Index::Fields::EAD_ID` is facetable as it's currently indexed.
