### ISSUE TITLE
Double hr appearing on some portal landing pages

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-public#394]
https://repository-pre.lib.duke.edu/dc/dukechapel

Perhaps due to collection guide info not appearing on this collection?

![screen shot 2016-05-17 at 1 47 46 pm](https://cloud.githubusercontent.com/assets/458247/15333080/34cafeae-1c36-11e6-8c2f-a664585dcb09.png)

**Comment by seanaery** [comment]
@corylown Yes, that's it. Good catch--that looks odd. I'll be able to fix it.
