### ISSUE TITLE
Additional file type icons needed

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-public#406]
I grabbed all the mime types from components on production to check how well our set of icons represents the ingested files. We have decent coverage. There are few file types we may want new icons for:

application/rtf
application/postscript
application/vnd.google-earth.kmz
application/vnd.google-earth.kml+xml
application/x-sas
message/rfc822
text/html

Currently any of the application types will get the binary.png icon, message/rfc822 gets the blank icon, and text/html gets the txt.png icon. I'm not sure we need special icons for all of these, but I think we may want ones for email, html, and maybe google earth.

What do you think, @mikedaul ?

**Comment by mikedaul** [comment]
Sounds good! I'll work on some options on Tuesday.


Thanks,


-Michael

________________________________

**Comment by mikedaul** [comment]
Here’s a first attempt at some new icons. Do these make sense to you?
 
I also thought we could repurpose the ‘code’ icon for html? Or should that look something like a webpage instead?
 
Thanks!
 
-Michael
 
PS – I think something is subtly off in terms of size between the various icons. I’m not quite sure what it is, but I’ll probably end up reexporting all of them at some point…

(postscript)
![icons_ps](https://cloud.githubusercontent.com/assets/2537019/15757379/41002c7c-28d3-11e6-83c6-79d9027b32db.png)

(kml)
![icons_kml](https://cloud.githubusercontent.com/assets/2537019/15757378/40fc68c6-28d3-11e6-9869-579d7c0745c7.png)

(kml + xml)
![icons_kml-xml](https://cloud.githubusercontent.com/assets/2537019/15757384/411d679c-28d3-11e6-9c54-797bfc33c397.png)

(sas)
![icons_x-sas](https://cloud.githubusercontent.com/assets/2537019/15757380/41018450-28d3-11e6-9a1b-93e6c8ddf083.png)

(rtf)
![icons_rtf](https://cloud.githubusercontent.com/assets/2537019/15757383/4113ed52-28d3-11e6-8b54-ffb067e6ced3.png)

(rfc-822)
![icons_rfc822](https://cloud.githubusercontent.com/assets/2537019/15757381/4102e34a-28d3-11e6-8159-7c3281cf01e0.png)

('code' - reuse for html?)
![icons_code](https://cloud.githubusercontent.com/assets/2537019/15757382/4108424a-28d3-11e6-9450-23c36249237a.png)

**Comment by corylown** [comment]
For the kml/xml and html files would it make sense to replace the curly braces with an empty tag to represent markup </>?

I think the others work great as is.

**Comment by mikedaul** [comment]
Thanks Cory - what do you think of these?

![icons_code](https://cloud.githubusercontent.com/assets/2537019/15785340/c847003c-2984-11e6-8f9e-c3fc89d3d904.png)

![icons_kml-xml](https://cloud.githubusercontent.com/assets/2537019/15785341/c84e7678-2984-11e6-9398-cefa3fc15ba8.png)

Also, I've got everything all perfectly sized and aligned now, so once we're happy with this latest round I'll just create updated versions for everything else too.

Thanks,

-Michael

**Comment by corylown** [comment]
I think these look great. Thanks for making them!

**Comment by seanaery** [comment]
Agreed -- excellent!

**Comment by mikedaul** [comment]
Hi Cory - here's a zip of all of the 'fixed' icons.
[icons.zip](https://github.com/duke-libraries/ddr-public/files/300682/icons.zip)

Hopefully everything is named the same as the previous versions.

**Comment by corylown** [comment]
Thanks!
