### ISSUE TITLE
Sidebar context design is unclear

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-public#413]
From testfest feed

right-hand list of stuff on the item screen is a little weird looking:

Like, what does Rubenstein Library mean in this context? What about the collection title?

When you're on the component page, this makes a little more sense, as the right hand then displays "part of item," but on previous pages, it does not read "part of collection"

![righthand](https://cloud.githubusercontent.com/assets/458247/15758418/83405936-28d8-11e6-8eb0-f9fea80499aa.PNG)

**Comment by seanaery** [comment]
This is primarily an issue for collections outside of the digital collections admin set. Here are a few more examples of different views (with various sidebar data present or not) that present a confusing UI.

![screen shot 2016-08-26 at 2 34 08 pm](https://cloud.githubusercontent.com/assets/3933756/18016471/9054bbee-6b9a-11e6-9a7b-520938806173.png)
![screen shot 2016-08-26 at 2 34 00 pm](https://cloud.githubusercontent.com/assets/3933756/18016472/905559e6-6b9a-11e6-9029-ee27d98e758f.png)
![screen shot 2016-08-26 at 2 33 34 pm](https://cloud.githubusercontent.com/assets/3933756/18016473/90610084-6b9a-11e6-8aeb-a2c51d4d7f1b.png)

**Comment by seanaery** [comment]
Here's a first html/css mockup of an improved sidebar. I could create in a branch here for live testing if helpful. cc: @corylown @mikedaul 


**Item Page**
![sidebar2-item](https://cloud.githubusercontent.com/assets/3933756/18053594/41773232-6dce-11e6-8437-57486cba4714.png)


**File (Component) Page**
![sidebar2-component](https://cloud.githubusercontent.com/assets/3933756/18053608/53be851c-6dce-11e6-9f96-cf540ebeb4f2.png)

**Comment by seanaery** [comment]
Additional idea with a "You Are Here" marker. 
![screen shot 2016-08-29 at 1 55 20 pm](https://cloud.githubusercontent.com/assets/3933756/18061371/7efd19ba-6df0-11e6-8269-1890f3fec179.png)

And a view with no descriptive snippet for collection.
![screen shot 2016-08-29 at 1 56 21 pm](https://cloud.githubusercontent.com/assets/3933756/18061373/82d6a3ee-6df0-11e6-98d3-d945e1f550dd.png)

**Comment by seanaery** [comment]
Some other variations using vertical lines & indentation.

**Centered**
![sidebar-centered](https://cloud.githubusercontent.com/assets/3933756/18066166/2a63e252-6e05-11e6-87d5-bbcc1754ff6f.png)

**Icons, Left-Justified**
![sidebar-icons-nolines](https://cloud.githubusercontent.com/assets/3933756/18066195/4d1a7356-6e05-11e6-8c97-be49c692370b.png)

**Icons, Left-Justified w/Lines**
![sidebar-leftjustify-lines](https://cloud.githubusercontent.com/assets/3933756/18066218/606145fc-6e05-11e6-974d-3e71f60ae9c2.png)

**Icons, Hierarchical w/Lines**
![sidebar-hierarchy-lines](https://cloud.githubusercontent.com/assets/3933756/18066223/6b8581b4-6e05-11e6-9e65-8dea3014ff62.png)

**Comment by mikedaul** [comment]
I really like the 'Centered' option - I think it's the most obvious and I also really like the design. Maybe try incorporating the icons as well?

'Icons, Hierarchical w/Lines' is really great too, nice design, easy to understand.

I think the 'Icons, Left-Justified w/Lines' is stronger and easier to comprehend at a glance than the 'Icons, Left-Justified'

Really nice work!

**Comment by corylown** [comment]
I agree with Michael that the centered option is a really effective design. The lines with the circles really help to illustrate the hierarchy. I also like the use of icons in some of the other options and think maybe they would work with the centered option too.
