### ISSUE TITLE
permalink wraps awkwardly at smaller viewports

### ISSUE THREAD

**Issue by seanaery** [duke-libraries/ddr-public#461]
Reported by @mikedaul -- the permalink value is pretty long, and so wraps awkwardly at some viewports.

![permalink_wrap2](https://cloud.githubusercontent.com/assets/3933756/17906717/805d4c8e-6946-11e6-9e7f-9421a6770c42.png)

**Comment by dchandekstark** [comment]
Transitioning to idn.duke.edu should help somewhat :).
